# name: Mocha CI

# on:
#   pull_request:
#     branches:
#       - master

# jobs:
#   check:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v1
#     - name: Install
#       run: npm install
#     - name : Test
#       run: npm run test
